grafana:
  adminPassword: "Nhom_DevOps_123!"
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec: {}
    additionalScrapeConfigs:
      - job_name: ansible-node-exporter
        static_configs:
          - targets:
              - "10.0.3.233:9100"
            labels:
              instance: "bastion"

alertmanager:
  enabled: true