apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db | quote }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  ports:
  - port: {{ .Values.postgres.port }}
  selector:
    app: postgres-db