apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: backend-user-secret
  namespace: {{ .Release.Namespace }}

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: backend-user-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.backendUser.awsSecretName }}
        property: DB_PASSWORD