apiVersion: v1
kind: Secret
metadata:
  name: backend-user-secret
  labels:
    {{ include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backendUser.secrets.DB_PASSWORD | quote }}
---
