# Base image python
FROM python:3.11-slim

# Tạo thư mục app
WORKDIR /app

# Copy requirements trước để cache layer
COPY requirements.txt .

# Cài dependency
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Expose port
EXPOSE 3003

# Run Flask app
CMD ["python", "server.py"]