# ==============================
# Stage 1: Build bằng Maven
# ==============================
FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /build

# copy pom trước để cache dependency
COPY pom.xml .
RUN mvn -B -q -e -DskipTests dependency:go-offline

# copy source code
COPY src ./src

# build jar
RUN mvn clean package -DskipTests


# ==============================
# Stage 2: Run app
# ==============================
FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

# copy jar từ stage build
COPY --from=builder /build/target/*.jar app.jar

# mở port
EXPOSE 3002

# chạy spring boot
ENTRYPOINT ["java","-jar","app.jar"]