spring.application.name=productservice
spring.data.mongodb.uri=mongodb+srv://23521581_db_user:atlas23521581@secondcluster.zdf5ent.mongodb.net/Product?retryWrites=true&w=majority

# Chỉ log mức WARN trở lên
logging.level.root=WARN

# Tắt log Mongo driver
logging.level.org.mongodb.driver=ERROR

# Tắt log Spring Web
logging.level.org.springframework.web=ERROR

logging.level.root=ERROR
logging.level.com.example.productservice=INFO
spring.main.banner-mode=off

server.port=3002
server.address=0.0.0.0
