spring.application.name=productservice
spring.data.mongodb.uri=mongodb+srv://23521581_db_user:atlas23521581@secondcluster.zdf5ent.mongodb.net/Product?retryWrites=true&w=majority

# Chỉ log mức WARN trở lên
logging.level.root=WARN

# Tắt log Mongo driver
logging.level.org.mongodb.driver=ERROR

# Tắt log Spring Web
logging.level.org.springframework.web=ERROR

logging.level.root=ERROR
logging.level.com.example.productservice=INFO
spring.main.banner-mode=off

server.port=3004

# backend_Product/src/main/resources/application.properties
# Product Service chạy trên port 3002
server.port=3002

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=product-service
management.metrics.tags.environment=production