# backend_Product/src/main/resources/application.properties
spring.application.name=productservice
spring.data.mongodb.uri=mongodb+srv://23521581_db_user:atlas23521581@secondcluster.zdf5ent.mongodb.net/Product?retryWrites=true&w=majority

# ================== LOGGING ==================
logging.level.root=ERROR
logging.level.com.example.productservice=INFO
logging.level.org.mongodb.driver=ERROR
logging.level.org.springframework.web=ERROR
spring.main.banner-mode=off

# ================== SERVER ==================
server.port=3002

# ================== ACTUATOR / PROMETHEUS ==================
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=product-service
management.metrics.tags.environment=production