[mgmt_host]
bastion ansible_host=15.135.219.61 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=/Users/hovuongtuongvy/Downloads/devops-sydney-01.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'